export const CHANGE_CHOOSEN_AREA = 'CHANGE_CHOOSEN_AREA';
export const CHANGE_CHOOSEN_NUMBER = 'CHANGE_CHOOSEN_NUMBER';
export const RESET_CHOOSEN_NUMBER = 'RESET_CHOOSEN_NUMBER';
export const FILL_AREA = 'FILL_AREA';
export const GENERATE_NEW_FIELD = 'GENERATE_NEW_FIELD';
export const CONTINUE_PLAY = 'CONTINUE_PLAY';
